workflows upgrade vcpkg once per day only
 - also added upgrading vcpkg in analyzers.yml

diff --git a/.github/workflows/analyzers.yml b/.github/workflows/analyzers.yml
--- a/.github/workflows/analyzers.yml
+++ b/.github/workflows/analyzers.yml
@@ -11,6 +11,9 @@ on: workflow_dispatch
 concurrency:
   group: tinyorm-linux
 
+env:
+  TINY_VCPKG_NEEDS_UPGRADE: false
+
 jobs:
 
   analyzers:
@@ -105,6 +108,43 @@ jobs:
         echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
         echo 'VCPKG_DEFAULT_TRIPLET=x64-linux-dynamic' >> $GITHUB_ENV
         echo 'VCPKG_MAX_CONCURRENCY=${{ env.TinyParallel }}' >> $GITHUB_ENV
+
+    - name: vcpkg needs upgrade? (once per day)
+      run: |
+        vcpkgUpgradedAtFilepath='${{ runner.workspace }}/.vcpkg_upgraded_at'
+
+        if [ ! -f "$vcpkgUpgradedAtFilepath" ] || [ ! -r "$vcpkgUpgradedAtFilepath" ] || \
+          ! read datePreviousUpgradeRaw < "$vcpkgUpgradedAtFilepath"
+        then
+          echo 'TINY_VCPKG_NEEDS_UPGRADE=true' >> $GITHUB_ENV
+          exit 0
+        fi
+
+        datePreviousUpgrade=$(date --date="$datePreviousUpgradeRaw" +%s)
+
+        if [ $? -ne 0 ] || [ -z "$datePreviousUpgrade" ]; then
+          echo "Parsing the '.vcpkg_upgraded_at' failed." >&2
+          exit 1
+        fi
+
+        dateToday=$(date --date=$(date +%Y-%m-%d) +%s)
+
+        if [ "$datePreviousUpgrade" -lt "$dateToday" ]; then
+          echo 'TINY_VCPKG_NEEDS_UPGRADE=true' >> $GITHUB_ENV
+        fi
+
+    - name: vcpkg upgrade repository (latest version)
+      if: env.TINY_VCPKG_NEEDS_UPGRADE == 'true'
+      run: |
+        cd "$VCPKG_INSTALLATION_ROOT"
+
+        git switch master
+        git fetch --tags origin
+        git reset --hard origin/master
+
+        ./bootstrap-vcpkg.sh
+
+        date +%Y-%m-%d > '${{ runner.workspace }}/.vcpkg_upgraded_at'
 
     - name: ${{ matrix.qt.name }} prepare environment
       run: |
diff --git a/.github/workflows/linux-qt6-drivers.yml b/.github/workflows/linux-qt6-drivers.yml
--- a/.github/workflows/linux-qt6-drivers.yml
+++ b/.github/workflows/linux-qt6-drivers.yml
@@ -17,6 +17,9 @@ on: workflow_dispatch
 concurrency:
   group: tinyorm-linux
 
+env:
+  TINY_VCPKG_NEEDS_UPGRADE: false
+
 # I will not remove the build folders before a job execution it's not necessary and
 # it will be faster this way. I can still remove them manually if needed or
 # if something goes wrong.
@@ -120,7 +123,32 @@ jobs:
         echo 'VCPKG_DEFAULT_TRIPLET=x64-linux-dynamic' >> $GITHUB_ENV
         echo 'VCPKG_MAX_CONCURRENCY=${{ env.TinyParallel }}' >> $GITHUB_ENV
 
+    - name: vcpkg needs upgrade? (once per day)
+      run: |
+        vcpkgUpgradedAtFilepath='${{ runner.workspace }}/.vcpkg_upgraded_at'
+
+        if [ ! -f "$vcpkgUpgradedAtFilepath" ] || [ ! -r "$vcpkgUpgradedAtFilepath" ] || \
+          ! read datePreviousUpgradeRaw < "$vcpkgUpgradedAtFilepath"
+        then
+          echo 'TINY_VCPKG_NEEDS_UPGRADE=true' >> $GITHUB_ENV
+          exit 0
+        fi
+
+        datePreviousUpgrade=$(date --date="$datePreviousUpgradeRaw" +%s)
+
+        if [ $? -ne 0 ] || [ -z "$datePreviousUpgrade" ]; then
+          echo "Parsing the '.vcpkg_upgraded_at' failed." >&2
+          exit 1
+        fi
+
+        dateToday=$(date --date=$(date +%Y-%m-%d) +%s)
+
+        if [ "$datePreviousUpgrade" -lt "$dateToday" ]; then
+          echo 'TINY_VCPKG_NEEDS_UPGRADE=true' >> $GITHUB_ENV
+        fi
+
     - name: vcpkg upgrade repository (latest version)
+      if: env.TINY_VCPKG_NEEDS_UPGRADE == 'true'
       run: |
         cd "$VCPKG_INSTALLATION_ROOT"
 
@@ -129,6 +157,8 @@ jobs:
         git reset --hard origin/master
 
         ./bootstrap-vcpkg.sh
+
+        date +%Y-%m-%d > '${{ runner.workspace }}/.vcpkg_upgraded_at'
 
     - name: CMake print version
       run: |
