workflows enhanced synchronous execution
 - handled error states
 - taken into account disabled workflows (disabled_manually state)

[skip ci]

diff --git a/.github/workflows/vcpkg-linux-drivers.yml b/.github/workflows/vcpkg-linux-drivers.yml
--- a/.github/workflows/vcpkg-linux-drivers.yml
+++ b/.github/workflows/vcpkg-linux-drivers.yml
@@ -477,10 +477,18 @@ jobs:
     # and all others will be canceled.
     # Jobs are run randomly! They are sorted from 0 to strategy.job-total - 1 in GitHub UI, so
     # the first job has index 0, the second job has index 1, ...
+    # Execute the next workflow inly if it's active and isn't disabled (disabled_manually state).
+    # Also, if the step fails due to any error, continue (eg. network unreachable or similar).
     - name: Run analyzers.yml workflows
+      continue-on-error: true
       if: strategy.job-index == 0
       working-directory: ${{ env.TinyORMPath }}
       run: |
-        gh workflow run analyzers.yml --ref ${{ github.ref_name }}
+        workflowState=$(gh workflow list --all --json path,state \
+        --jq '.[] | select (.path | endswith("/analyzers.yml")) | .state')
+
+        if [ $? -eq 0 ] && [[ "$workflowState" == 'active' ]]; then
+          gh workflow run analyzers.yml --ref ${{ github.ref_name }}
+        fi
       env:
         GH_TOKEN: ${{ github.token }}
